### ISSUE TITLE
Добавить поддержку TS для frontend приложения

### ISSUE THREAD

**Issue by olegnowikow** [Glebuc/fitness_centr_fullstack#1]
Необходимо добавить поддержку TypeScript:
1. TypeScript предоставляет статический анализ кода, что позволяет выявлять ошибки на этапе разработки, до запуска приложения. Это снижает вероятность возникновения ошибок и упрощает отладку;
2. Облегчит масштабирование приложения, т.к. с увеличением его размера становится сложнее контролировать типы данных;
3. Многие библиотеки для React имеют официальную поддержку TypeScript, что упрощает интеграцию.

**Comment by Glebuc** [comment]
Front-end реализован с поддержкой TS 

"@types/node": "^16.18.58",
"@types/react": "^18.2.28",
"@types/react-dom": "^18.2.13",
